export const SEARCH_CHARACTERS_REQUEST = "SEARCH_CHARACTERS_REQUEST";
export const SEARCH_CHARACTERS_SUCCESS = "SEARCH_CHARACTERS_SUCCESS";
export const SEARCH_CHARACTERS_FAILURE = "SEARCH_CHARACTERS_FAILURE";
